### PR TITLE
OPENTOK-39220: Upgrade to 2.16

### PR DESCRIPTION
**Pull request by jtiet**
## Pull request checklist

- [ ] All tests pass. Demo project builds and runs.
- [ ] I have resolved any merge conflicts. Confirmation: ____

## What's in this pull request?

>...

### CODE REVIEW

**Comment by marinaserranomontes** [comment]
@jtiet please could you update the core lib version as well?  Current versionName is "1.0.21"

**Comment by jtiet** [comment]
Thanks, I've changed the lib to reflect the new version now.

**Comment by guness** [comment]
are you sure this one works, because it was not working on some devices when I force Gradle to use updated core.

**Comment by jtiet** [comment]
@guness It looks like v2.15/v2.16 introduces some regression in the accelerator core project. Engineering is aware of the issue and is working on it at the moment.

**Comment by marinaserranomontes** [comment]
Updated version https://github.com/opentok/accelerator-core-android/pull/91

**Pull request closed without merging**
